[package]
name = "e04"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
euler = { version = "0.2.0", git = "https://github.com/wells1632/euler-rust.git" }
